const CANVAS_WIDTH = 1200
const CANVAS_HEIGHT = 720
const MENU_UPGRADE_WIDTH = 300
const MENU_UPGRADE_MARGIN = 50

const INVINCIBILITY_TIME = 3
const LASER_SHOOTING_RATE = 2
const LASER_RANGE = 500

export {
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    MENU_UPGRADE_WIDTH,
    MENU_UPGRADE_MARGIN,
    INVINCIBILITY_TIME,
    LASER_SHOOTING_RATE,
    LASER_RANGE,
}
